/*
 * Copyright 2022 Victor Malone (vm19171).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package WindowsAndPanels;

import InnerWorkings.ExportGame;
import DataItems.ProjectFile;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * Window used for changing settings before exporting the finished game. 
 * 
 * @author Victor Malone (vm19171)
 */
public class ExportWindow extends javax.swing.JFrame {

    /**
     * Creates new form ExportWindow
     */
    public ExportWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        exportGame = new InnerWorkings.ExportGame();
        exportLocationChooser = new javax.swing.JFileChooser();
        themeButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        exportLabel = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        ternaryPanel = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        themeLabel = new javax.swing.JLabel();
        bookThemeButton = new javax.swing.JRadioButton();
        darkThemeButton = new javax.swing.JRadioButton();
        saveLabel = new javax.swing.JLabel();
        chooseLocationButton = new javax.swing.JButton();

        exportLocationChooser.setAcceptAllFileFilterUsed(false);
        exportLocationChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        exportLocationChooser.setApproveButtonText("Export Here");
        exportLocationChooser.setDialogTitle("Export To");
        exportLocationChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        exportLabel.setFont(new java.awt.Font("DFPOP1-W9", 0, 48)); // NOI18N
        exportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exportLabel.setText("<html>  <u>Export</u> </html> ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("So, you've made it this far! Congratulations on the creation of your new masterpiece! \n\n   Before you can play, you need to export your game. \n   To do so, choose a theme below, a location to export to, and then Make your CHOICE!\n   It will be saved as a collection of HTML files in a folder named after your game.\n\n   Once you've successfully exported your experience, you can play it by navigating to the folder you saved it\n   in, and opening the file named after the ID of your starting page.   \n\n   If you'd like to share your creation with a friend, simply send them the entire folder containing all the pages      of your game.\n\n   Make sure to include the resources folder as well! Have fun! ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jTextArea1.setHighlighter(null);
        jTextArea1.setRequestFocusEnabled(false);

        exportButton.setFont(new java.awt.Font("DFPOP1-W9", 0, 18)); // NOI18N
        exportButton.setText("Make your CHOICE!");
        exportButton.setEnabled(false);
        exportButton.setMaximumSize(new java.awt.Dimension(220, 30));
        exportButton.setMinimumSize(new java.awt.Dimension(220, 30));
        exportButton.setPreferredSize(new java.awt.Dimension(220, 30));
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        ternaryPanel.add(exportButton);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        themeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        themeLabel.setText("Choose a theme for your game:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(themeLabel, gridBagConstraints);

        themeButtonGroup.add(bookThemeButton);
        bookThemeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bookThemeButton.setSelected(true);
        bookThemeButton.setText("Storybook Theme");
        bookThemeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel1.add(bookThemeButton, gridBagConstraints);

        themeButtonGroup.add(darkThemeButton);
        darkThemeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        darkThemeButton.setText("Dark Theme");
        darkThemeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel1.add(darkThemeButton, gridBagConstraints);

        saveLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveLabel.setText("And somewhere to save it:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        jPanel1.add(saveLabel, gridBagConstraints);

        chooseLocationButton.setText("Choose Export Location...");
        chooseLocationButton.setMaximumSize(new java.awt.Dimension(185, 22));
        chooseLocationButton.setMinimumSize(new java.awt.Dimension(185, 22));
        chooseLocationButton.setPreferredSize(new java.awt.Dimension(185, 22));
        chooseLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLocationButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel1.add(chooseLocationButton, gridBagConstraints);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportLabel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ternaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(exportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ternaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        this.export();
    }//GEN-LAST:event_exportButtonActionPerformed

    private void chooseLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLocationButtonActionPerformed

        try {
            int returnValue = exportLocationChooser.showSaveDialog(this);

            if (returnValue == JFileChooser.APPROVE_OPTION)
            {
                System.out.println("Export location successfully set.");
                exportButton.setEnabled(true);
            }
            else
            {
                System.out.println("Export location was not set successfully. Try again.");
                exportButton.setEnabled(false);
            }
        } catch (java.awt.HeadlessException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_chooseLocationButtonActionPerformed

    /**
     * Creates a new ExportGame object and sets its theme. It then creates a new folder at the designated location, sets the ExportGame object's project file, and exports the game.
     */
    public void export()
    {
        exportGame = new ExportGame();
        
        // determine theme based on radio buttons
        if (bookThemeButton.isSelected())
        {
         exportGame.setTheme("book");
        }
        else
        {
            exportGame.setTheme("dark");
        }
        
        System.out.println("Export method of ExportWindow called.");
        // System.out.println("Sending project file and output location to ExportGame object...");
        String outputFolder = exportLocationChooser.getSelectedFile().getAbsolutePath();
        System.out.println("Output Folder: " + outputFolder);
        outputFolder += "/" + exportGame.cleanProjectName(project.getProjectTitle());  // add generated folder extension to path
        System.out.println("New Location: " + outputFolder);
        exportGame.setOutputFolder(outputFolder);
        exportGame.setProject(project);
        exportGame.export();
        
        JOptionPane.showMessageDialog(this, "Well done! Your game was created successfully!");
    }
    
    // Getters and Setters
    
    public ProjectFile getProject() {
        return project;
    }

    public void setProject(ProjectFile project) {
        this.project = project;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportWindow().setVisible(true);
            }
        });
    }
    
    /**
     * ProjectFile used for exportation.
     */
    private ProjectFile project;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bookThemeButton;
    private javax.swing.JButton chooseLocationButton;
    private javax.swing.JRadioButton darkThemeButton;
    private javax.swing.JButton exportButton;
    private InnerWorkings.ExportGame exportGame;
    private javax.swing.JLabel exportLabel;
    private javax.swing.JFileChooser exportLocationChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel saveLabel;
    private javax.swing.JPanel ternaryPanel;
    private javax.swing.ButtonGroup themeButtonGroup;
    private javax.swing.JLabel themeLabel;
    // End of variables declaration//GEN-END:variables

}
