/*
 * Copyright 2022 Victor Malone (vm19171).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package WindowsAndPanels;

import InnerWorkings.ExportGame;
import DataItems.ProjectFile;
import javax.swing.JFileChooser;

/**
 *
 * @author Victor Malone (vm19171)
 */
public class ExportWindow extends javax.swing.JFrame {

    /**
     * Creates new form ExportWindow
     */
    public ExportWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportGame = new InnerWorkings.ExportGame();
        exportLocationChooser = new javax.swing.JFileChooser();
        themeButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        exportLabel = new javax.swing.JLabel();
        titlePageCheckbox = new javax.swing.JCheckBox();
        authorNameField = new javax.swing.JTextField();
        chooseLocationButton = new javax.swing.JButton();
        authorNameCheckbox = new javax.swing.JCheckBox();
        bookThemeButton = new javax.swing.JRadioButton();
        darkThemeButton = new javax.swing.JRadioButton();
        infoLabel = new javax.swing.JLabel();
        secondaryPanel = new javax.swing.JPanel();
        exportButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        exportLocationChooser.setAcceptAllFileFilterUsed(false);
        exportLocationChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        exportLocationChooser.setApproveButtonText("Export Here");
        exportLocationChooser.setDialogTitle("Export To");
        exportLocationChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        exportLabel.setFont(new java.awt.Font("DFPOP1-W9", 0, 48)); // NOI18N
        exportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exportLabel.setText("<html>  <u>Export</u> </html> ");

        titlePageCheckbox.setText("Generate Title Page");
        titlePageCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlePageCheckboxActionPerformed(evt);
            }
        });

        authorNameField.setText("Author Name");

        chooseLocationButton.setText("Choose Export Location...");
        chooseLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLocationButtonActionPerformed(evt);
            }
        });

        authorNameCheckbox.setText("Display Author Name");

        themeButtonGroup.add(bookThemeButton);
        bookThemeButton.setSelected(true);
        bookThemeButton.setText("Storybook Theme");

        themeButtonGroup.add(darkThemeButton);
        darkThemeButton.setText("Dark Theme");

        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("<html> Include info here! Things like how to play(and let others play), what the game is comprised of, how to edit, etc. <br> The program will create a folder, export pages into said folder, and copy image files into a 'resource' folder within that folder.  Any preexisting materials will be replaced. </html> ");

        exportButton.setText("Make your CHOICE!");
        exportButton.setEnabled(false);
        exportButton.setMaximumSize(new java.awt.Dimension(137, 30));
        exportButton.setMinimumSize(new java.awt.Dimension(137, 30));
        exportButton.setPreferredSize(new java.awt.Dimension(137, 30));
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });
        secondaryPanel.add(exportButton);

        jLabel1.setText("Theme:");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportLabel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseLocationButton)
                            .addComponent(titlePageCheckbox)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(authorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(authorNameCheckbox))
                            .addComponent(darkThemeButton)
                            .addComponent(bookThemeButton)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(secondaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(exportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(titlePageCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(authorNameCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(authorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(bookThemeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(darkThemeButton)
                        .addGap(34, 34, 34)
                        .addComponent(chooseLocationButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(infoLabel)))
                .addGap(27, 27, 27)
                .addComponent(secondaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void titlePageCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlePageCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titlePageCheckboxActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        this.export();
    }//GEN-LAST:event_exportButtonActionPerformed

    private void chooseLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLocationButtonActionPerformed
       
        try {
            int returnValue = exportLocationChooser.showSaveDialog(this);
            
            if (returnValue == JFileChooser.APPROVE_OPTION)
            {
                System.out.println("Export location successfully set.");
                exportButton.setEnabled(true);
            }
            else
            {
                System.out.println("Export location was not set successfully. Try again.");
                exportButton.setEnabled(false);
            }
        } catch (java.awt.HeadlessException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_chooseLocationButtonActionPerformed

    
    public void export()
    {
        exportGame = new ExportGame();
        
        // determine theme based on radio buttons
        if (bookThemeButton.isSelected())
        {
         exportGame.setTheme("book");
        }
        else
        {
            exportGame.setTheme("dark");
        }
        
        System.out.println("Export method of ExportWindow called.");
        // System.out.println("Sending project file and output location to ExportGame object...");
        String outputFolder = exportLocationChooser.getSelectedFile().getAbsolutePath();
        System.out.println("Output Folder: " + outputFolder);
        outputFolder += "/" + exportGame.cleanProjectName(project.getProjectTitle());  // add generated folder extension to path
        System.out.println("New Location: " + outputFolder);
        exportGame.setOutputFolder(outputFolder);
        exportGame.setProject(project);
        exportGame.export();
    }
    
    public ProjectFile getProject() {
        return project;
    }

    public void setProject(ProjectFile project) {
        this.project = project;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportWindow().setVisible(true);
            }
        });
    }
    
    private ProjectFile project;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox authorNameCheckbox;
    private javax.swing.JTextField authorNameField;
    private javax.swing.JRadioButton bookThemeButton;
    private javax.swing.JButton chooseLocationButton;
    private javax.swing.JRadioButton darkThemeButton;
    private javax.swing.JButton exportButton;
    private InnerWorkings.ExportGame exportGame;
    private javax.swing.JLabel exportLabel;
    private javax.swing.JFileChooser exportLocationChooser;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel secondaryPanel;
    private javax.swing.ButtonGroup themeButtonGroup;
    private javax.swing.JCheckBox titlePageCheckbox;
    // End of variables declaration//GEN-END:variables

}
