/*
 * Copyright 2022 Victor Malone (vm19171).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package WindowsAndPanels;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Vic Malone
 */
public class StartMenuWindow extends javax.swing.JFrame {

    /**
     * Creates new form StartMenuGUI
     */
    public StartMenuWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileDialog = new javax.swing.JFileChooser(System.getProperty("user.dir"));
        welcomeLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        newProjectButton = new javax.swing.JButton();
        openProjectButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        creditsButton = new javax.swing.JButton();

        openFileDialog.setDialogTitle("Open Project");
        openFileDialog.setFileFilter(new InnerWorkings.CHOICEFileFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Condensed Hypertext Orgnization Interface for the Creation of Experiences)");
        setBackground(new java.awt.Color(61, 70, 77));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("DFPOP1-W9", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(770, 540));
        setResizable(false);
        setSize(new java.awt.Dimension(770, 540));

        welcomeLabel.setFont(new java.awt.Font("DFPOP1-W9", 1, 48)); // NOI18N
        welcomeLabel.setText("<html> <u>Welcome to CHOICE!</u>  ");

        buttonPanel.setPreferredSize(new java.awt.Dimension(650, 435));
        buttonPanel.setLayout(new java.awt.GridLayout(2, 2, 15, 15));

        newProjectButton.setFont(new java.awt.Font("DFPOP1-W9", 0, 60)); // NOI18N
        newProjectButton.setText("<html> New <br> Project");
        newProjectButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        newProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newProjectButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        newProjectButton.setFocusPainted(false);
        newProjectButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(newProjectButton);

        openProjectButton.setFont(new java.awt.Font("DFPOP1-W9", 0, 60)); // NOI18N
        openProjectButton.setText("<html> Open <br> Project...");
        openProjectButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        openProjectButton.setFocusPainted(false);
        openProjectButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        openProjectButton.setMargin(new java.awt.Insets(2, 14, 2, 2));
        openProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(openProjectButton);

        settingsButton.setFont(new java.awt.Font("DFPOP1-W9", 0, 60)); // NOI18N
        settingsButton.setText("Settings");
        settingsButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        settingsButton.setFocusPainted(false);
        settingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settingsButton.setMargin(new java.awt.Insets(2, 14, 2, 2));
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(settingsButton);

        creditsButton.setFont(new java.awt.Font("DFPOP1-W9", 0, 60)); // NOI18N
        creditsButton.setText("Credits");
        creditsButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        creditsButton.setFocusPainted(false);
        creditsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        creditsButton.setMargin(new java.awt.Insets(2, 14, 2, 2));
        creditsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(creditsButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void creditsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsButtonActionPerformed
        System.out.println("4th button pressed.");
        JOptionPane.showMessageDialog(buttonPanel, "Here's where the credits will go!");
    }//GEN-LAST:event_creditsButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        System.out.println("Settings button pressed.");
        JOptionPane.showMessageDialog(buttonPanel, "You pressed the Settings button! Unfortunately, this feature has not yet been implemented. Please look forward to the 2.0 release!");
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void openProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectButtonActionPerformed
        try {
            int returnValue = openFileDialog.showOpenDialog(this);
            System.out.println(""); // for clarity

            if (returnValue == JFileChooser.APPROVE_OPTION) {
                System.out.println("Load approved!");
                
                EditorWindow editorWindow = new EditorWindow();
                editorWindow.getAppHandler().loadProject(openFileDialog.getSelectedFile());
                editorWindow.setTitle(editorWindow.getAppHandler().getProjectFile().getProjectTitle());
                editorWindow.getDragAndDropPanel().setNodes(editorWindow.getAppHandler().getNodes());
                editorWindow.getDragAndDropPanel().repaint();
                editorWindow.setVisible(true);
                
                // dispose of start window
                this.dispose();
            }
            else {
                System.out.println("Load not approved...");
            }

        }
        catch (java.awt.HeadlessException e1) {
            e1.printStackTrace();
        }
        catch (IOException | ClassNotFoundException ex) {
            System.out.println("There was a problem loading the file.");
            Logger.getLogger(EditorWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_openProjectButtonActionPerformed

    private void newProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectButtonActionPerformed
        System.out.println("New Project button pressed.");
        // JOptionPane.showMessageDialog(buttonPanel, "You pressed the New Project button!");

        EditorWindow editorWindow = new EditorWindow();
        editorWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newProjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set theFlatLaf Dark look and feel. Then, try Nimbus if not found. If not, then just stick with default. */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            boolean darkFound = false;
            
            try {
                        UIManager.setLookAndFeel( new FlatDarkLaf() );
                        darkFound = true;
                        
                    } catch( Exception ex ) {
                        darkFound = false;
                        System.err.println( "Failed to initialize FlatLaF." );
                    }
            
            if (darkFound != true)
            {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        System.out.println("Nimbus set as LaF.");
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenuWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        // attempt to load custom font
        URL fontURL;
        try {
            File fontFile = new File("master_resources\\DFPop91.ttf");
            Font dfpopFont = Font.createFont(Font.TRUETYPE_FONT, fontFile);

            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            env.registerFont(dfpopFont);
        }
        catch (IOException ex) {
            Logger.getLogger(StartMenuWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (FontFormatException ex) {
            Logger.getLogger(StartMenuWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenuWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel buttonPanel;
    javax.swing.JButton creditsButton;
    javax.swing.JButton newProjectButton;
    javax.swing.JFileChooser openFileDialog;
    javax.swing.JButton openProjectButton;
    javax.swing.JButton settingsButton;
    javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
