# Build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: The Condensed Hypertext Organization Interface for the Creation of Experiences
description: CHOICE is a a hypertext game creation tool built in Java.
