/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EditorWindow;

import javax.swing.JOptionPane;
import InnerWorkings.DragAndDrop;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JViewport;
import javax.swing.SwingUtilities;

/**
 *
 * @author rolep
 */
public class EditorWindow extends javax.swing.JFrame {

    public DragAndDrop mainEditor;
    
    
    /**
     * Creates new form EditorWindowGUI
     */
    public EditorWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        openProjectChooser = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        dragAndDrop1 = new InnerWorkings.DragAndDrop();
        editorSideBar = new javax.swing.JPanel();
        nodeTitlePanel = new javax.swing.JPanel();
        pageEditorLabel = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        paragraphPanel = new javax.swing.JPanel();
        paragraphTextLabel = new javax.swing.JLabel();
        nodeParagraphScrollPane = new javax.swing.JScrollPane();
        nodeParagraphField = new javax.swing.JTextArea();
        nodeIDPanel = new javax.swing.JPanel();
        IDLabel = new java.awt.Label();
        nodeIDField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        buttonMenuPanel = new javax.swing.JPanel();
        createNodeButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        editorMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileMenuNew = new javax.swing.JMenuItem();
        fileMenuOpen = new javax.swing.JMenuItem();
        fileMenuProjectSettings = new javax.swing.JMenuItem();
        fileMenuExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        editMenuUndo = new javax.swing.JMenuItem();
        editMenuRedo = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setResizeWeight(1.0);
        jSplitPane1.setToolTipText("");

        dragAndDrop1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout dragAndDrop1Layout = new javax.swing.GroupLayout(dragAndDrop1);
        dragAndDrop1.setLayout(dragAndDrop1Layout);
        dragAndDrop1Layout.setHorizontalGroup(
            dragAndDrop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        dragAndDrop1Layout.setVerticalGroup(
            dragAndDrop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
        );

        mainEditor = dragAndDrop1;

        jSplitPane1.setLeftComponent(dragAndDrop1);

        editorSideBar.setBackground(new java.awt.Color(255, 153, 153));
        editorSideBar.setMaximumSize(new java.awt.Dimension(500, 32767));
        editorSideBar.setLayout(new java.awt.GridBagLayout());

        nodeTitlePanel.setForeground(new java.awt.Color(0, 0, 0));
        nodeTitlePanel.setFont(new java.awt.Font("DFPOP1-W9", 0, 12)); // NOI18N

        pageEditorLabel.setAlignment(java.awt.Label.CENTER);
        pageEditorLabel.setBackground(new java.awt.Color(255, 255, 255));
        pageEditorLabel.setFont(new java.awt.Font("DFPOP1-W9", 0, 36)); // NOI18N
        pageEditorLabel.setText("Page Editor");

        jTextField1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Page Title");
        jTextField1.setPreferredSize(new java.awt.Dimension(97, 26));

        javax.swing.GroupLayout nodeTitlePanelLayout = new javax.swing.GroupLayout(nodeTitlePanel);
        nodeTitlePanel.setLayout(nodeTitlePanelLayout);
        nodeTitlePanelLayout.setHorizontalGroup(
            nodeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nodeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(pageEditorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(nodeTitlePanelLayout.createSequentialGroup()
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(222, 222, 222)
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        nodeTitlePanelLayout.setVerticalGroup(
            nodeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nodeTitlePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(nodeTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pageEditorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        editorSideBar.add(nodeTitlePanel, gridBagConstraints);

        paragraphPanel.setForeground(new java.awt.Color(0, 0, 0));

        paragraphTextLabel.setFont(new java.awt.Font("DFPOP1-W9", 0, 18)); // NOI18N
        paragraphTextLabel.setText("Paragraph Text:");

        nodeParagraphField.setColumns(20);
        nodeParagraphField.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nodeParagraphField.setLineWrap(true);
        nodeParagraphField.setRows(5);
        nodeParagraphField.setText("Write your story here...");
        nodeParagraphField.setWrapStyleWord(true);
        nodeParagraphScrollPane.setViewportView(nodeParagraphField);

        javax.swing.GroupLayout paragraphPanelLayout = new javax.swing.GroupLayout(paragraphPanel);
        paragraphPanel.setLayout(paragraphPanelLayout);
        paragraphPanelLayout.setHorizontalGroup(
            paragraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paragraphPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(paragraphTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paragraphPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nodeParagraphScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        paragraphPanelLayout.setVerticalGroup(
            paragraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paragraphPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(paragraphTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nodeParagraphScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editorSideBar.add(paragraphPanel, gridBagConstraints);

        nodeIDPanel.setFont(new java.awt.Font("DFPOP1-W9", 0, 18)); // NOI18N

        IDLabel.setFont(new java.awt.Font("DFPOP1-W9", 0, 18)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(187, 187, 187));
        IDLabel.setText("Page ID:");

        nodeIDField.setText("AutoGeneratedIDGoesHere");
        nodeIDField.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent component)
            {

                JTextField field = (JTextField)component;
                String input = field.getText();
                // allow alphanumeric and underscore chars only
                Pattern regex = Pattern.compile("^[a-zA-Z0-9_]+$");
                Matcher matcher = regex.matcher(input);

                if (matcher.matches())
                { 
                    /*
                    component.setComponent(input); */
                    return true;
                } 
                else
                {
                    // remove all unacceptable characters
                    // String resultingInput = input.replaceAll("[^a-zA-Z0-9_]", "");
                    // component.setText(resultingInput);
                    return false;   // just return true here too?
                }
            }

            @Override
            public boolean shouldYieldFocus(JComponent component)
            {
                boolean isValid = verify(component);

                if (isValid)
                {
                    component.setToolTipText(null);
                }
                else
                {
                    component.setToolTipText("IDs may only contain alphanumeric characters(A-Z, a-z, 0-9) and underscores(_).");
                }

                return isValid;
            }

        });
        nodeIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeIDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nodeIDPanelLayout = new javax.swing.GroupLayout(nodeIDPanel);
        nodeIDPanel.setLayout(nodeIDPanelLayout);
        nodeIDPanelLayout.setHorizontalGroup(
            nodeIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nodeIDPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nodeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        nodeIDPanelLayout.setVerticalGroup(
            nodeIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nodeIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nodeIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nodeIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editorSideBar.add(nodeIDPanel, gridBagConstraints);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editorSideBar.add(jPanel1, gridBagConstraints);

        jSplitPane1.setRightComponent(editorSideBar);

        buttonMenuPanel.setBackground(new java.awt.Color(255, 255, 102));

        createNodeButton.setText("Create Node");
        createNodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNodeButtonActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout buttonMenuPanelLayout = new javax.swing.GroupLayout(buttonMenuPanel);
        buttonMenuPanel.setLayout(buttonMenuPanelLayout);
        buttonMenuPanelLayout.setHorizontalGroup(
            buttonMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createNodeButton)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonMenuPanelLayout.setVerticalGroup(
            buttonMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buttonMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNodeButton)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        fileMenuNew.setText("New...");
        fileMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuNewActionPerformed(evt);
            }
        });
        menuFile.add(fileMenuNew);

        fileMenuOpen.setText("Open...");
        fileMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuOpenActionPerformed(evt);
                fileMenuOpenActionPerformed1(evt);
            }
        });
        menuFile.add(fileMenuOpen);

        fileMenuProjectSettings.setText("Project Settings");
        fileMenuProjectSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuProjectSettingsActionPerformed(evt);
            }
        });
        menuFile.add(fileMenuProjectSettings);

        fileMenuExit.setText("Exit");
        fileMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuExitActionPerformed(evt);
            }
        });
        menuFile.add(fileMenuExit);

        editorMenu.add(menuFile);

        menuEdit.setText("Edit");

        editMenuUndo.setText("Undo");
        editMenuUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuUndoActionPerformed(evt);
            }
        });
        menuEdit.add(editMenuUndo);

        editMenuRedo.setText("Redo");
        menuEdit.add(editMenuRedo);

        editorMenu.add(menuEdit);

        menuView.setText("View");
        editorMenu.add(menuView);

        setJMenuBar(editorMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addComponent(buttonMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuNewActionPerformed
        System.out.println("File menu: New button pressed.");
        // JOptionPane.showMessageDialog(editorPanel, "You pressed the New menu option!");
    }//GEN-LAST:event_fileMenuNewActionPerformed

    private void fileMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuOpenActionPerformed

    private void editMenuUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuUndoActionPerformed

    private void fileMenuProjectSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuProjectSettingsActionPerformed
        new ProjectSettingsMenu().setVisible(true);
    }//GEN-LAST:event_fileMenuProjectSettingsActionPerformed

    private void fileMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fileMenuExitActionPerformed

    private void fileMenuOpenActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuOpenActionPerformed1
        try {
            openProjectChooser.showOpenDialog(this);
        } catch (java.awt.HeadlessException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_fileMenuOpenActionPerformed1

    private void createNodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNodeButtonActionPerformed
        System.out.println("JButton1 pressed! This is how the user will be able to add new nodes.");
        mainEditor.addNode(100, 100);
    }//GEN-LAST:event_createNodeButtonActionPerformed

    private void nodeIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodeIDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label IDLabel;
    private javax.swing.JPanel buttonMenuPanel;
    private javax.swing.JButton createNodeButton;
    private InnerWorkings.DragAndDrop dragAndDrop1;
    private javax.swing.JMenuItem editMenuRedo;
    private javax.swing.JMenuItem editMenuUndo;
    private javax.swing.JMenuBar editorMenu;
    private javax.swing.JPanel editorSideBar;
    private javax.swing.JMenuItem fileMenuExit;
    private javax.swing.JMenuItem fileMenuNew;
    private javax.swing.JMenuItem fileMenuOpen;
    private javax.swing.JMenuItem fileMenuProjectSettings;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuView;
    private javax.swing.JTextField nodeIDField;
    private javax.swing.JPanel nodeIDPanel;
    private javax.swing.JTextArea nodeParagraphField;
    private javax.swing.JScrollPane nodeParagraphScrollPane;
    private javax.swing.JPanel nodeTitlePanel;
    private javax.swing.JFileChooser openProjectChooser;
    private java.awt.Label pageEditorLabel;
    private javax.swing.JPanel paragraphPanel;
    private javax.swing.JLabel paragraphTextLabel;
    // End of variables declaration//GEN-END:variables
}
