/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EditorWindowPackage;

import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Victor Malone (vm19171)
 */
public class LinkPanel extends javax.swing.JPanel {

    /**
     * Creates new form choiceEntryPanel
     */
    public LinkPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceChooserBox = new javax.swing.JComboBox<>();
        choiceTextField = new javax.swing.JTextField();
        linkLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 34));

        choiceChooserBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[There are no available pages to link to.]" }));
        choiceChooserBox.setToolTipText("What page should this one link to?");
        choiceChooserBox.setMaximumSize(new java.awt.Dimension(243, 22));
        choiceChooserBox.setPrototypeDisplayValue("eeeeeeeeeeeeeeeeeeeeeeee");

        choiceTextField.setText("jTextField1");
        choiceTextField.setMinimumSize(new java.awt.Dimension(30, 22));
        choiceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceTextFieldActionPerformed(evt);
            }
        });

        linkLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        linkLabel.setText("Link to page with ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceChooserBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(choiceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(choiceChooserBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choiceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choiceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choiceTextFieldActionPerformed
 
    
    
    public void setComboBoxModel(ComboBoxModel m)
    {
        this.choiceChooserBox.setModel(m);
    }
    
    public void setSelectedID(String s)
    {
        this.choiceChooserBox.setSelectedItem(s);
    }
    
    public void setHyperlinkText(String s)
    {
        this.choiceTextField.setText(s);
    }
    
    
    
    
    // Getters and Setters
      public JComboBox<String> getChoiceChooserBox() {
        return choiceChooserBox;
    }

    public void setChoiceChooserBox(JComboBox<String> choiceChooserBox) {
        this.choiceChooserBox = choiceChooserBox;
    }

    public JTextField getChoiceTextField() {
        return choiceTextField;
    }

    public void setChoiceTextField(JTextField choiceTextField) {
        this.choiceTextField = choiceTextField;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choiceChooserBox;
    private javax.swing.JTextField choiceTextField;
    private javax.swing.JLabel linkLabel;
    // End of variables declaration//GEN-END:variables
}
