/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EditorPopup;

/**
 *
 * @author rolep
 */
public class EditorPopupWindow extends javax.swing.JFrame {

    /**
     * Creates new form EditorPopupGUI
     */
    public EditorPopupWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorBasePanel = new javax.swing.JPanel();
        passageIDPanel = new javax.swing.JPanel();
        passageIDLabel = new javax.swing.JLabel();
        passageIDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        passageIDLabel1 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        bodyPanel = new javax.swing.JPanel();
        passageIDLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        imagePanel = new javax.swing.JPanel();
        passageIDLabel3 = new javax.swing.JLabel();
        choicePanel = new javax.swing.JPanel();
        passageIDLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 600));
        setResizable(false);

        editorBasePanel.setMinimumSize(new java.awt.Dimension(570, 720));
        editorBasePanel.setPreferredSize(new java.awt.Dimension(570, 725));

        passageIDLabel.setFont(new java.awt.Font("DFPOP1-W9", 0, 24)); // NOI18N
        passageIDLabel.setText("Passage ID:");

        passageIDField.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        passageIDField.setText("jTextField1");
        passageIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passageIDFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        jLabel1.setText("This is the ID used to refer to the current passage.");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout passageIDPanelLayout = new javax.swing.GroupLayout(passageIDPanel);
        passageIDPanel.setLayout(passageIDPanelLayout);
        passageIDPanelLayout.setHorizontalGroup(
            passageIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passageIDPanelLayout.createSequentialGroup()
                .addGroup(passageIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passageIDPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(passageIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passageIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passageIDPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        passageIDPanelLayout.setVerticalGroup(
            passageIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passageIDPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(passageIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passageIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passageIDField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        editorBasePanel.add(passageIDPanel);

        passageIDLabel1.setFont(new java.awt.Font("DFPOP1-W9", 0, 24)); // NOI18N
        passageIDLabel1.setText("Title:");

        titleField.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        titleField.setText("New Passage");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(passageIDLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passageIDLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleField))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        editorBasePanel.add(titlePanel);

        passageIDLabel2.setFont(new java.awt.Font("DFPOP1-W9", 0, 24)); // NOI18N
        passageIDLabel2.setText("Body:");

        jEditorPane1.setFont(new java.awt.Font("DFPOP1-W9", 0, 14)); // NOI18N
        jEditorPane1.setText("Body paragraph goes here.");
        jEditorPane1.setDragEnabled(true);
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(passageIDLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(passageIDLabel2))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        editorBasePanel.add(bodyPanel);

        passageIDLabel3.setFont(new java.awt.Font("DFPOP1-W9", 0, 24)); // NOI18N
        passageIDLabel3.setText("Image:");

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(passageIDLabel3)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(passageIDLabel3)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        editorBasePanel.add(imagePanel);

        passageIDLabel4.setFont(new java.awt.Font("DFPOP1-W9", 0, 24)); // NOI18N
        passageIDLabel4.setText("Choices:");

        javax.swing.GroupLayout choicePanelLayout = new javax.swing.GroupLayout(choicePanel);
        choicePanel.setLayout(choicePanelLayout);
        choicePanelLayout.setHorizontalGroup(
            choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choicePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(passageIDLabel4)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        choicePanelLayout.setVerticalGroup(
            choicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choicePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(passageIDLabel4)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        editorBasePanel.add(choicePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editorBasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editorBasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passageIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passageIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passageIDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorPopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorPopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorPopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorPopupWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorPopupWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel choicePanel;
    private javax.swing.JPanel editorBasePanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField passageIDField;
    private javax.swing.JLabel passageIDLabel;
    private javax.swing.JLabel passageIDLabel1;
    private javax.swing.JLabel passageIDLabel2;
    private javax.swing.JLabel passageIDLabel3;
    private javax.swing.JLabel passageIDLabel4;
    private javax.swing.JPanel passageIDPanel;
    private javax.swing.JTextField titleField;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
